### ISSUE TITLE
Apply to Journal entries

### ISSUE THREAD

**Issue by Reddlar** [BlitzKraig/fvtt-VoiceActor#1]
Hi there love the module! Would it be possible to add this voice actor module to journal entries as well? When making just generic/important NPCs  as just journal entries, with a photo. Making 2 entries to have a journal with general backstory or important info and then an npc token for that same person that will probably never be used if they are never needed on a map just makes it take up extra space. So having the ability to just add a voice clip to these would be really helpful. Thank you for the hard work

**Comment by BlitzKraig** [comment]
Hi, thanks for the feedback!

It should be pretty easy for me to add this in theory, and I can definitely understand the use-case.

I'll take a look at it tomorrow.

Thanks again

**Comment by BlitzKraig** [comment]
Hi Reddlar,

Please try 0.0.8 and let me know if that's what you were after.

Thanks for the suggestion!
