### ISSUE TITLE
Error opening non-main actor sheet items

### ISSUE THREAD

**Issue by RollToSaveVsDragons** [BlitzKraig/fvtt-VoiceActor#16]
I get this error every time I open a sheet or item that isn't the main actor sheet, including ex. journals.

<img width="382" alt="Screenshot 2022-03-18 at 00 13 27" src="https://user-images.githubusercontent.com/5146879/158912314-1d10a901-a079-4c3c-b8ba-87539e16f2ca.png">

**Comment by BlitzKraig** [comment]
Fixed
