### ISSUE TITLE
Recordings are cut short in Firefox

### ISSUE THREAD

**Issue by nathonius** [BlitzKraig/fvtt-VoiceActor#6]
Seems specific to Firefox as it works fine in Chrome. The recording is extremely clipped, max length of maybe half a second. Playback of files recorded in Chrome works in Firefox so it seems like a recording issue.

**Comment by nathonius** [comment]
I tracked it down, looks like this is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1696794

Remediation seems to be to set a timeslice value < 250ms on the `.start()` call to start recording. Alternately, just wait until they fix it, since it looks like a PR went up today to patch it. 😁 It was just bugging me, so I wanted to figure it out.

**Comment by BlitzKraig** [comment]
Thanks for the feedback, and the work to debug! I'll keep an eye on this, and make any tweaks if they're needed.

**Comment by nathonius** [comment]
Fixed in Firefox 88.
