### ISSUE TITLE
Recordings seem to only store about 25% or the time you record

### ISSUE THREAD

**Issue by gkankstech** [BlitzKraig/fvtt-VoiceActor#7]
I was having issues where my recordings were being truncated very early so I did some experimentation.

I am using Firefox and the UI is prompting me to allow the microphone.

If I record for 30 seconds (about when the recording feature times out in the UI) I get 7 seconds max of voice recording. If I record for 10 seconds I get about 3 seconds of recording. This behavior is the same when recording for an actor and for a Journal entry.

I know there's a ten second limit on an actor but I would have expected it to time out at that time and to record the full time. Instead in both cases it stops the recording at 30 seconds and only keeps about a quarter of the elapsed time.

**Comment by BlitzKraig** [comment]
Hi, thanks for the feedback.

This sounds like a previously reported issue:
https://github.com/BlitzKraig/fvtt-VoiceActor/issues/6

Can you confirm?
